print ("Welcome to the Elite 101 Chatbot!")
name = input ("Please enter your name: ")
age = input ("Nice to meet you, " + name + "! How old are you? ")
print ("Welcome " + name + "!  Oh, to be " + age + " again! How can I help you today? ")
print("1. Placeholder Option 1")
print("2. Placeholder Option 2")
print("3. Placeholder Option 3")
print("4. Exit the conversation")
choice = input ("Please choose from the following options: ")
if choice == "4":
 print("Goodbye! ")
